services:
  - type: web
    name: librechat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
